server.port: 8080
dataPath: C:\vnhnbackup\yyyymmdd
sqlPath:  C:\vnhnbackup\sql
uploadPath: C:\vnhnbackup\bkupload

sqlfiles:
  sql:
    - AACT_TRX_BAL
    - AACT_TRX_BASE
    - AACT_TRX_BS
    - AACT_TRX_PL
    - ACOM_CIX_BASE
    - ACOM_CIX_LOCAL
    - ACOM_COMH_MSG
    - ACOM_COMH_MSGHIS
    - ACOM_COMH_TAGLINE
    - ACOM_COMH_USER
    - ACOM_COM_ACTCD
    - ACOM_COM_ALLOW
    - ACOM_COM_CCY
    - ACOM_COM_FEERT
    - ACOM_COM_FPBODY
    - ACOM_COM_FPHEAD
    - ACOM_COM_VOUCHER
    - ACOM_CONT_BASE
    - ACOM_DMH_ALLOC
    - ACOM_DMH_ALLOCHIS
    - ACOM_DMH_BASE
    - ACOM_DMH_HIS
    - ACOM_EPB_BASE
    - ACOM_EPB_HIS
    - ACOM_EPB_ITM
    - ACOM_EPB_RPT
    - ACOM_FAB_HIS
    - ACOM_FAB_ITM
    - ACOM_LMT_BASEACT
    - ACOM_LMT_BASEHD
    - ACOM_LMT_BASEHIS
    - ACOM_LMT_BOJ
    - ACOM_LMT_CLMIT
    - ACOM_LMT_ITM
    - ACOM_LMT_SIL
    - ACOM_LMT_SILHIS
    - ADST_DPB_BASE
    - ADST_DPB_BURI
    - ADST_DPB_CERT
    - ADST_DPB_DROK
    - ADST_DPB_HEJI
    - ADST_DPB_HIS
    - ADST_DPB_INFO
    - ADST_DPB_INRT
    - ADST_DPB_INTM
    - ADST_DPB_TRAN
    - ADST_DPB_YEDE
    - ADST_LNB_AGR
    - ADST_LNB_BASE
    - ADST_LNB_FEE
    - ADST_LNB_HIS
    - ADST_LNB_INT
    - ADST_LNB_ITM
    - ADST_LNB_REPAY
    - ADST_LNB_SCH
    - AFEX_ADH_AMEND
    - AFEX_ADH_BASE
    - AFEX_ADH_HIS
    - AFEX_ADH_ITM
    - AFEX_BFH_BASE
    - AFEX_BFH_HIS
    - AFEX_BFH_PAY
    - AFEX_IPB_AMD
    - AFEX_IPB_BASE
    - AFEX_IPB_BLD
    - AFEX_IPB_BLK
    - AFEX_IPB_BOJ
    - AFEX_IPB_DJB
    - AFEX_IPB_DJH
    - AFEX_IPB_LGM
    - AFEX_IPH_AMD
    - AFEX_IPH_ATAG
    - AFEX_IPH_BASE
    - AFEX_IPH_BTAG
    - AFEX_IPH_COVER
    - AFEX_IPH_HIS
    - AFEX_RCH_BAL
    - AFEX_RCH_BASE
    - AFEX_RCH_PEND
    - AFEX_RCH_RECON
    - AFEX_RCH_SEQNO
    - AFEX_RCH_TRAN
    - AFEX_RCH_VOSTRO
    - AFEX_RIH_BASE
    - AFEX_RIH_HIS
    - AFEX_RIH_REFUND
    - AFEX_ROB_AMD
    - AFEX_ROH_BASE
    - AFEX_ROH_HIS
    - AFEX_RTB_BASE
    - AFEX_RTB_HIS
    - AFEX_RTB_HSS
    - AFEX_XPB_ADV
    - AFEX_XPB_AMD
    - AFEX_XPB_BASE
    - AFEX_XPB_BDM
    - AFEX_XPB_BDS
    - AFEX_XPB_HIS
    - AFEX_XPB_ITM
    - AFEX_XPB_LGM
    - AFEX_XPB_RENEDT
    - AFEX_XPH_CA
    - AFEX_XPH_COVER
    - AFEX_XPH_COVER_RESEND
    - AFEX_XPH_RENEGO
    - AFEX_XPH_SHIP
    - AFEX_XPH_SHIP_RESEND
    - AFEX_XPH_TRA
    - AFIF_FEH_BASE
    - AFIF_FEH_HIS
    - AFIF_MMH_BASE
    - AFIF_MMH_HIS
    - AFIF_MTH_BASE
    - AFIF_MTH_HIS
    - AFTR_FFH_COMM_TRSC_PTCL
    - ADST_DPB_GYUL
    - ACOM_DTG_CONT_STS
    - ACOM_DTG_NAPAS_HIS
    - ACOM_ATB_APPLY
    - ACOM_ATB_BASE
    - ACOM_DTG_NAPAS_RECON
